version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    networks:
      - nanu
    command: 'npm run dev'
    depends_on:
      - db

  db:
    image: mongo:6.0
    # ports:
    #   - 27017:27017
    networks:
      - nanu

networks:
  nanu:
    driver: bridge

